<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Basic access check: only admins should access this page
if (!isset($_SESSION['user']) || $_SESSION['user']->role !== 'admin') {
    header('Location: ../../views/security/LoginForm.php');
    exit;
}

// Expect variables from controller: $voucherCode, $voucherId, $svgContent, $fileName
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Voucher QR Preview - NGear</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet">
    <link rel="stylesheet" href="../css/AllTables.css">
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            background-color: #f3f4f6;
            margin: 0;
            padding: 0;
        }

        .qr-page-container {
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 1.5rem;
        }

        .qr-card {
            background-color: #ffffff;
            border-radius: 0.75rem;
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
            padding: 1.75rem 2rem;
            max-width: 480px;
            width: 100%;
            text-align: center;
        }

        .qr-title {
            font-size: 1.25rem;
            font-weight: 600;
            margin-bottom: 0.75rem;
            color: #111827;
        }

        .qr-subtitle {
            font-size: 0.9rem;
            color: #6b7280;
            margin-bottom: 1.5rem;
        }

        .qr-code-wrapper {
            display: inline-flex;
            padding: 1rem;
            border-radius: 0.75rem;
            background-color: #f9fafb;
            border: 1px solid #e5e7eb;
            margin-bottom: 1.5rem;
        }

        .qr-code-wrapper svg {
            width: 220px;
            height: 220px;
            display: block;
        }

        .qr-code-text {
            font-size: 0.95rem;
            color: #374151;
            margin-bottom: 1.5rem;
        }

        .qr-actions {
            display: flex;
            gap: 0.75rem;
            justify-content: center;
            flex-wrap: wrap;
        }

        .qr-btn-primary,
        .qr-btn-secondary {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            gap: 0.25rem;
            padding: 0.6rem 1.2rem;
            border-radius: 0.5rem;
            font-size: 0.9rem;
            font-weight: 500;
            text-decoration: none;
            border: none;
            cursor: pointer;
            transition: all 0.2s ease;
        }

        .qr-btn-primary {
            background-color: #FF523B;
            color: #ffffff;
        }

        .qr-btn-primary:hover {
            background-color: #e63e27;
        }

        .qr-btn-secondary {
            background-color: #e5e7eb;
            color: #374151;
        }

        .qr-btn-secondary:hover {
            background-color: #d1d5db;
        }
    </style>
</head>

<body>
    <div class="qr-page-container">
        <div class="qr-card">
            <h1 class="qr-title">Voucher QR Code</h1>
            <p class="qr-subtitle">
                Scan this QR code or download it as an image. It encodes the voucher code:
                <strong><?php echo htmlspecialchars($voucherCode, ENT_QUOTES); ?></strong>
            </p>

            <div class="qr-code-wrapper">
                <?php
                // SVG is safe to output as-is because it is generated by a trusted library
                echo $svgContent;
                ?>
            </div>

            <p class="qr-code-text">
                File name suggestion: <strong><?php echo htmlspecialchars($fileName, ENT_QUOTES); ?></strong>
            </p>

            <div class="qr-actions">
                <a
                    class="qr-btn-primary"
                    href="../controller/VoucherController.php?action=downloadVoucherQr&amp;voucher_id=<?php echo (int)$voucherId; ?>&amp;code=<?php echo urlencode($voucherCode); ?>">
                    <span class="material-symbols-outlined">download</span>
                    <span>Download QR</span>
                </a>

                <a
                    class="qr-btn-secondary"
                    href="../controller/VoucherController.php?action=showAll">
                    <span class="material-symbols-outlined">arrow_back</span>
                    <span>Back to All Vouchers</span>
                </a>
            </div>
        </div>
    </div>
</body>

</html>


