CREATE TABLE IF NOT EXISTS users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    gender ENUM('Male','Female','Other') DEFAULT 'Other',
    contact_no VARCHAR(20),
    email VARCHAR(100) NOT NULL UNIQUE,
    profile_photo MEDIUMBLOB,
    DateOfBirth DATE NOT NULL,
    password VARCHAR(255) NOT NULL,
    reset_otp VARCHAR(6) NULL,
    reset_otp_expires_at DATETIME NULL,
    role ENUM('member','admin') DEFAULT 'member',
    status ENUM('active','inactive','banned','blocked') DEFAULT 'active',
    failed_login_attempts INT DEFAULT 0,
    last_failed_login DATETIME NULL,
    last_login_at DATETIME NULL,
    email_verified BOOLEAN DEFAULT FALSE,
    verification_token VARCHAR(255) NULL,
    token_expires_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
